Config = {}

Config.DiscordUrl_banlogs =
    "https://discord.com/api/webhooks/877576828590620703/oyC-4KBItmWdyN8BT4xt3h7mWKGXlVEu8sWVe1ePZfIYSSW4j5rM8F7z3wyq2hKyNPNg"

Config.DiscordUrl_messgaes =
    "https://discord.com/api/webhooks/915288906298171472/7hL5ttpc-D6NEyY4czwlk6KGyLjVpYTbGz60Bz4MsqgJEfJaXcrJ0nnIXixXyW_5gopM"

Config.DiscordUrl_HallOfShame =
    "https://discord.com/api/webhooks/938108626390884452/lcPurpM5E1Z00m4Yt4qBqH6HmUzFXwekKP5kiYzk91TZxTSOr3b_0smRaqkjDSpl8GEm"

Config.sendDiscordlog_Banlogs = true

Config.anticar = true

Config.antigodmode = true

Config.checkingplayerrun = true

-- Resource
Config.AntiResourceStart = true
Config.AntiResourceStop = true
Config.AntiResourceNeuStart = true
Config.AntiTriggerEvents = true

Config.BlackListedEvents = {}
-- Soon more Events
Config.AntiInjection = true

Config.forbiddenkeys = true
Config.AntiBombDamage = true
Config.AntiWeapons = {
    inhand = true --Checks if the Player have a Blacklistet weapon in his hand
}

Config.AntiBlips = true
Config.superjump = true

Config.steammustbeallowed = true
Config.BlacklistedCommands = {
    "haha",
    "lol",
    "xddd",
    "chocolate",
    "panickey",
    "jolmany",
    "killmenu"
}
Config.Blacklistetkeys = {
    121,
    213,
    214
}

Config.blacklistetcarlist = {
    "vigilante",
    "hydra",
    "deluxo",
    "avenger",
    "akula",
    "apc",
    "barrage",
    "caracara",
    "cargobob",
    "chernobog",
    "hunter",
    "insurgent",
    "starling",
    "lazer",
    "bombushka",
    "savage",
    "rhino",
    "khanjali"
}
Config.Blacklistetweaponslist = {
    -- List of all Blacklistet Weapons
    "WEAPON_APPISTOL",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_ASSAULTSHOTGUN",
    "WEAPON_BZGAS",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_BULLPUPRIFLE_MK2",
    "WEAPON_BULLPUPSHOTGUN",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_COMBATMG",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_COMPACTLAUNCHER",
    "WEAPON_DOUBLEACTION",
    "WEAPON_DBSHOTGUN",
    "WEAPON_FIREWORK",
    "WEAPON_FLARE",
    "WEAPON_FLAREGUN",
    "WEAPON_GOLFCLUB",
    "WEAPON_GRENADE",
    "WEAPON_GRENADELAUNCHER",
    "WEAPON_GRENADELAUNCHER_SMOKE",
    "WEAPON_HEAVYSHOTGUN",
    "WEAPON_HEAVYSNIPER",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_HOMINGLAUNCHER",
    "WEAPON_MG",
    "WEAPON_MARKSMANPISTOL",
    "WEAPON_MARKSMANRIFLE",
    "WEAPON_MARKSMANRIFLE_MK2",
    "WEAPON_MINIGUN",
    "WEAPON_MOLOTOV",
    "WEAPON_NIGHTVISION",
    "WEAPON_PETROLCAN",
    "WEAPON_PIPEBOMB",
    "WEAPON_PISTOL50",
    "WEAPON_PISTOL_MK2",
    "WEAPON_POOLCUE",
    "WEAPON_PROXMINE",
    "WEAPON_PUMPSHOTGUN",
    "WEAPON_PUMPSHOTGUN_MK2",
    "WEAPON_RPG",
    "WEAPON_RAILGUN",
    "WEAPON_REVOLVER",
    "WEAPON_REVOLVER_MK2",
    "WEAPON_SMG_MK2",
    "WEAPON_SNSPISTOL_MK2",
    "WEAPON_SMOKEGRENADE",
    "WEAPON_SNIPERIFLE",
    "WEAPON_SPECIALCARBINE",
    "WEAPON_SPECIALCARBINE_MK2",
    "WEAPON_STICKYBOMB",
    "WEAPON_SWEEPERSHOTGUN",
    "WEAPON_RAYPISTOL",
    "WEAPON_RAYCARBINE",
    "WEAPON_RAYMINIGUN",
    "WEAPON_STONE_HATCHET"
}

Config.banplayer = false

Config.banmessage = {
    Blacklistetweapon = {
        inhand = "Du wurdest gebannt, da du eine nicht legale Waffe in der Hand hattest. Melde dich bitte im Support."
    }
}

Config.kickmessage = {
    godmodes = "[Noxans - AntiCheat]; Du wurdest Gekickt weil du GodMode an hattes",
    blacklistetcar = "[Noxans - AntiCheat]; Du wurdest gebannt, da du in einem Auto warst, welches Blacklistet ist.",
    Blacklistetweapon = {
        inhand = "[Noxans - AntiCheat]; Du wurdest gekickt, da du eine illegale Waffe in der Hand hattest. Melde dich bitte im Support mit einem Clip."
    },
    keys = "[Noxans - AntiCheat]; Du hast einen Key benutzt welcher nicht erlaubt war. ",
    kickmessagecommand = "[Noxans - AntiCheat]; Du wurdest gekickt, da du einen Komischen Command eingegeben hast. Melde dich bitte mit einem Clip im Support.",
    antijump = "[Noxans - AntiCheat]; Du wurdest gekickt, da du zu weit gesprungen bist. Melde dich bitte mit einem Clip im Support. ",
    fastrun = "[Noxans - AntiCheat]; Du wurdest gekickt, da du zu schnell gerannt bist. Melde dich bitte mit einem Clip im Support.",
    fastcar = "[Noxans - AntiCheat]; Du wurdest gebannt, da du einen SpeedHack aktiviert hattest. Melde dich bitte mit einem Clip im Support."
}
registeredEvents = {}

fakeEvents = {
    -- ESX Events
    "esx:getSharedObject",
    "esx_ambulancejob:revive",
    "esx_society:openBossMenu",
    "esx_status:set",
    "esx_policejob:handcuff",
    "esx_jailer:wysylandoo",
    "esx_godirtyjob:pay",
    "esx_pizza:pay",
    "esx_slotmachine:sv:2",
    "esx_banksecurity:pay",
    "esx_gopostaljob:pay",
    "esx_truckerjob:pay",
    "esx_carthief:pay",
    "esx_garbagejob:pay",
    "esx_ranger:pay",
    "esx_truckersjob:payy",
    "esx_blanchisseur:washMoney",
    "esx_moneywash:withdraw",
    "esx_blanchisseur:startWhitening",
    "esx_billing:sendBill",
    "esx_dmvschool:pay",
    "esx_jailer:sendToJail",
    "esx_jailler:sendToJail",
    "esx-qalle-jail:jailPlayer",
    "esx-qalle-jail:jailPlayerNew",
    "esx_jailer:sendToJailCatfrajerze",
    "esx_policejob:billPlayer",
    "esx_skin:openRestrictedMenu",
    "esx_inventoryhud:openPlayerInventory",
    -- Other Events
    "bank:transfer",
    "advancedFuel:setEssence",
    "tost:zgarnijsiano",
    "Sasaki_kurier:pay",
    "wojtek_ubereats:napiwek",
    "wojtek_ubereats:hajs",
    "xk3ly-barbasz:getfukingmony",
    "xk3ly-farmer:paycheck",
    "tostzdrapka:wygranko",
    "laundry:washcash",
    "projektsantos:mandathajs",
    "program-keycard:hacking",
    "6a7af019-2b92-4ec2-9435-8fb9bd031c26",
    "211ef2f8-f09c-4582-91d8-087ca2130157",
    "neweden_garage:pay",
    "8321hiue89js",
    "js:jailuser",
    "wyspa_jail:jailPlayer",
    "wyspa_jail:jail",
    "gcPhone:sendMessage",
    "ambulancier:selfRespawn",
    "UnJP"
}
Config.BlacklistedModels = {
    --VEHICLES
    "skylift",
    "valkyrie2",
    "airbus",
    "hunter",
    "bus",
    "armytanker",
    "armytrailer",
    "armytrailer2",
    "baletrailer",
    "boattrailer",
    "cablecar",
    "docktrailer",
    "freighttrailer",
    "graintrailer",
    "proptrailer",
    "raketrailer",
    "tr2",
    "tr3",
    "tr4",
    "trflat",
    "tvtrailer",
    "tanker2",
    "trailerlarge",
    "trailerlogs",
    "trailersmall",
    "trailers",
    "trailers2",
    "trailers3",
    "trailers4",
    "RHINO",
    "AKULA",
    "SAVAGE",
    "HUNTER",
    "BUZZARD",
    "BUZZARD2",
    "ANNIHILATOR",
    "VALKYRIE",
    "HYDRA",
    "APC",
    "Trailersmall2",
    "Lazer",
    "oppressor",
    "mogul",
    "barrage",
    "Khanjali",
    "volatol",
    "chernobog",
    "avenger",
    "stromberg",
    "nightshark",
    "besra",
    "babushka ",
    "starling",
    "insurgent",
    "cargobob",
    "cargobob2",
    "cargobob3",
    "cargobob4",
    "caracara",
    "deluxo",
    "menacer",
    "scramjet",
    "oppressor2",
    "revolter",
    "viseris",
    "savestra",
    "thruster",
    "ardent",
    "dune3",
    "tampa3",
    "halftrack",
    "nokota",
    "strikeforce",
    "bombushka",
    "molotok",
    "pyro",
    "ruiner2",
    "limo2",
    "technical",
    "technical2",
    "technical3",
    "jb700w",
    "blazer5",
    "insurgent3",
    "boxville5",
    "bruiser",
    "bruiser2",
    "bruiser3",
    "brutus",
    "brutus2",
    "brutus3",
    "cerberus",
    "cerberus2",
    "cerberus3",
    "dominator4",
    "dominator5",
    "dominator6",
    "impaler2",
    "impaler3",
    "impaler4",
    "issi4",
    "issi5",
    "issi6",
    "monster3",
    "monster4",
    "monster5",
    "scarab",
    "scarab2",
    "scarab3",
    "slamvan4",
    "slamvan5",
    "slamvan6",
    "zr380",
    "zr3802",
    "zr3803",
    "alphaz1",
    "avenger2",
    "blimp",
    "blimp2",
    "blimp3",
    "cargoplane",
    "cuban800",
    "dodo",
    "duster",
    "howard",
    "jet",
    "mammatus",
    "microlight",
    "miljet",
    "nimbus",
    "rogue",
    "seabreeze",
    "tug",
    "shamal",
    "stunt",
    "titan",
    "tula",
    "vestra",
    -- OBJECTS/PROPS
    "stt_prop_stunt_track_dwslope30",
    "prop_gas_tank_01a",
    "prop_gascyl_01a",
    "prop_cs_dildo_01",
    "prop_ld_toilet_01",
    "prop_ld_bomb_anim",
    "prop_ld_farm_couch01",
    "prop_gas_pump_1a",
    "prop_gas_pump_1b",
    "prop_gas_pump_1c",
    "prop_gas_pump_1d",
    "prop_gas_pump_old2",
    "prop_gas_pump_old3",
    "prop_vintage_pump",
    "hei_prop_carrier_radar_1_l1",
    "v_res_mexball",
    "prop_rock_1_a",
    "prop_rock_1_b",
    "prop_rock_1_c",
    "prop_rock_1_d",
    "prop_player_gasmask",
    "prop_rock_1_e",
    "prop_rock_1_f",
    "prop_rock_1_g",
    "prop_rock_1_h",
    "prop_test_boulder_01",
    "prop_test_boulder_02",
    "prop_test_boulder_03",
    "prop_test_boulder_04",
    "apa_mp_apa_crashed_usaf_01a",
    "ex_prop_exec_crashdp",
    "apa_mp_apa_yacht_o1_rail_a",
    "apa_mp_apa_yacht_o1_rail_b",
    "apa_mp_h_yacht_armchair_01",
    "apa_mp_h_yacht_armchair_03",
    "apa_mp_h_yacht_armchair_04",
    "apa_mp_h_yacht_barstool_01",
    "apa_mp_h_yacht_bed_01",
    "apa_mp_h_yacht_bed_02",
    "apa_mp_h_yacht_coffee_table_01",
    "apa_mp_h_yacht_coffee_table_02",
    "apa_mp_h_yacht_floor_lamp_01",
    "apa_mp_h_yacht_side_table_01",
    "apa_mp_h_yacht_side_table_02",
    "apa_mp_h_yacht_sofa_01",
    "apa_mp_h_yacht_sofa_02",
    "apa_mp_h_yacht_stool_01",
    "apa_mp_h_yacht_strip_chair_01",
    "apa_mp_h_yacht_table_lamp_01",
    "apa_mp_h_yacht_table_lamp_02",
    "apa_mp_h_yacht_table_lamp_03",
    "prop_flag_columbia",
    "apa_mp_apa_yacht_o2_rail_a",
    "apa_mp_apa_yacht_o2_rail_b",
    "apa_mp_apa_yacht_o3_rail_a",
    "apa_mp_apa_yacht_o3_rail_b",
    "apa_mp_apa_yacht_option1",
    "proc_searock_01",
    "apa_mp_h_yacht_",
    "apa_mp_apa_yacht_option1_cola",
    "apa_mp_apa_yacht_option2",
    "apa_mp_apa_yacht_option2_cola",
    "apa_mp_apa_yacht_option2_colb",
    "apa_mp_apa_yacht_option3",
    "apa_mp_apa_yacht_option3_cola",
    "apa_mp_apa_yacht_option3_colb",
    "apa_mp_apa_yacht_option3_colc",
    "apa_mp_apa_yacht_option3_cold",
    "apa_mp_apa_yacht_option3_cole",
    "apa_mp_apa_yacht_jacuzzi_cam",
    "apa_mp_apa_yacht_jacuzzi_ripple003",
    "apa_mp_apa_yacht_jacuzzi_ripple1",
    "apa_mp_apa_yacht_jacuzzi_ripple2",
    "apa_mp_apa_yacht_radar_01a",
    "apa_mp_apa_yacht_win",
    "prop_crashed_heli",
    "apa_mp_apa_yacht_door",
    "prop_shamal_crash",
    "xm_prop_x17_shamal_crash",
    "apa_mp_apa_yacht_door2",
    "apa_mp_apa_yacht",
    "prop_flagpole_2b",
    "prop_flagpole_2c",
    "prop_flag_canada",
    "apa_prop_yacht_float_1a",
    "apa_prop_yacht_float_1b",
    "apa_prop_yacht_glass_01",
    "apa_prop_yacht_glass_02",
    "apa_prop_yacht_glass_03",
    "apa_prop_yacht_glass_04",
    "apa_prop_yacht_glass_05",
    "apa_prop_yacht_glass_06",
    "apa_prop_yacht_glass_07",
    "apa_prop_yacht_glass_08",
    "apa_prop_yacht_glass_09",
    "apa_prop_yacht_glass_10",
    "prop_flag_canada_s",
    "prop_flag_eu",
    "prop_flag_eu_s",
    "prop_target_blue_arrow",
    "prop_target_orange_arrow",
    "prop_target_purp_arrow",
    "prop_target_red_arrow",
    "apa_prop_flag_argentina",
    "apa_prop_flag_australia",
    "apa_prop_flag_austria",
    "apa_prop_flag_belgium",
    "apa_prop_flag_brazil",
    "apa_prop_flag_canadat_yt",
    "apa_prop_flag_china",
    "apa_prop_flag_columbia",
    "apa_prop_flag_croatia",
    "apa_prop_flag_czechrep",
    "apa_prop_flag_denmark",
    "apa_prop_flag_england",
    "apa_prop_flag_eu_yt",
    "apa_prop_flag_finland",
    "apa_prop_flag_france",
    "apa_prop_flag_german_yt",
    "apa_prop_flag_hungary",
    "apa_prop_flag_ireland",
    "apa_prop_flag_israel",
    "apa_prop_flag_italy",
    "apa_prop_flag_jamaica",
    "apa_prop_flag_japan_yt",
    "apa_prop_flag_canada_yt",
    "apa_prop_flag_lstein",
    "apa_prop_flag_malta",
    "apa_prop_flag_mexico_yt",
    "apa_prop_flag_netherlands",
    "apa_prop_flag_newzealand",
    "apa_prop_flag_nigeria",
    "apa_prop_flag_norway",
    "apa_prop_flag_palestine",
    "apa_prop_flag_poland",
    "apa_prop_flag_portugal",
    "apa_prop_flag_puertorico",
    "apa_prop_flag_russia_yt",
    "apa_prop_flag_scotland_yt",
    "apa_prop_flag_script",
    "apa_prop_flag_slovakia",
    "apa_prop_flag_slovenia",
    "apa_prop_flag_southafrica",
    "apa_prop_flag_southkorea",
    "apa_prop_flag_spain",
    "apa_prop_flag_sweden",
    "apa_prop_flag_switzerland",
    "apa_prop_flag_turkey",
    "apa_prop_flag_uk_yt",
    "apa_prop_flag_us_yt",
    "apa_prop_flag_wales",
    "prop_flag_uk",
    "prop_flag_uk_s",
    "prop_flag_us",
    "prop_flag_usboat",
    "prop_flag_us_r",
    "prop_flag_us_s",
    "prop_flag_france",
    "prop_flag_france_s",
    "prop_flag_german",
    "prop_flag_german_s",
    "prop_flag_ireland",
    "prop_flag_ireland_s",
    "prop_flag_japan",
    "prop_flag_japan_s",
    "prop_flag_ls",
    "prop_flag_lsfd",
    "prop_flag_lsfd_s",
    "prop_flag_lsservices",
    "prop_flag_lsservices_s",
    "prop_flag_ls_s",
    "prop_flag_mexico",
    "prop_flag_mexico_s",
    "prop_flag_russia",
    "prop_flag_russia_s",
    "prop_flag_s",
    "prop_flag_sa",
    "prop_flag_sapd",
    "prop_flag_sapd_s",
    "prop_flag_sa_s",
    "prop_flag_scotland",
    "prop_flag_scotland_s",
    "prop_flag_sheriff",
    "prop_flag_sheriff_s",
    "prop_flag_uk",
    "prop_flag_uk_s",
    "prop_flag_us",
    "prop_flag_usboat",
    "prop_flag_us_r",
    "prop_flag_us_s",
    "prop_flamingo",
    "prop_swiss_ball_01",
    "prop_air_bigradar_l1",
    "prop_air_bigradar_l2",
    "prop_air_bigradar_slod",
    "p_fib_rubble_s",
    "prop_money_bag_01",
    "p_cs_mp_jet_01_s",
    "prop_poly_bag_money",
    "prop_air_radar_01",
    "hei_prop_carrier_radar_1",
    "prop_air_bigradar",
    "prop_carrier_radar_1_l1",
    "prop_asteroid_01",
    "prop_xmas_ext",
    "p_oil_pjack_01_amo",
    "p_oil_pjack_01_s",
    "p_oil_pjack_02_amo",
    "p_oil_pjack_03_amo",
    "p_oil_pjack_02_s",
    "p_oil_pjack_03_s",
    "prop_aircon_l_03",
    "prop_med_jet_01",
    "p_med_jet_01_s",
    "hei_prop_carrier_jet",
    "bkr_prop_biker_bblock_huge_01",
    "bkr_prop_biker_bblock_huge_02",
    "bkr_prop_biker_bblock_huge_04",
    "bkr_prop_biker_bblock_huge_05",
    "hei_prop_heist_emp",
    "prop_weed_01",
    "prop_air_bigradar",
    "prop_juicestand",
    "prop_lev_des_barge_02",
    "hei_prop_carrier_defense_01",
    "prop_aircon_m_04",
    "prop_mp_ramp_03",
    "lts_prop_lts_ramp_01",
    "lts_prop_lts_ramp_02",
    "lts_prop_lts_ramp_03",
    "prop_jetski_ramp_01",
    "prop_mp_ramp_01",
    "prop_mp_ramp_01_tu",
    "prop_mp_ramp_02",
    "prop_mp_ramp_02_tu",
    "prop_mp_ramp_03",
    "prop_mp_ramp_03_tu",
    "prop_skate_flatramp_cr",
    "stt_prop_ramp_adj_flip_m",
    "stt_prop_ramp_adj_flip_mb",
    "stt_prop_ramp_adj_flip_s",
    "stt_prop_ramp_adj_flip_sb",
    "stt_prop_ramp_adj_hloop",
    "stt_prop_ramp_adj_loop",
    "stt_prop_ramp_jump_l",
    "stt_prop_ramp_jump_m",
    "stt_prop_ramp_jump_s",
    "stt_prop_ramp_jump_xl",
    "stt_prop_ramp_jump_xs",
    "stt_prop_ramp_jump_xxl",
    "stt_prop_ramp_multi_loop_rb",
    "stt_prop_ramp_spiral_l",
    "stt_prop_ramp_spiral_l_l",
    "stt_prop_ramp_spiral_l_m",
    "stt_prop_ramp_spiral_l_s",
    "stt_prop_ramp_spiral_l_xxl",
    "stt_prop_ramp_spiral_m",
    "stt_prop_ramp_spiral_s",
    "stt_prop_ramp_spiral_xxl",
    "stt_prop_stunt_ramp",
    "stt_prop_stunt_wideramp",
    "stt_prop_stunt_track_dwslope15",
    "stt_prop_stunt_track_dwshort",
    "stt_prop_stunt_track_dwsh15",
    "stt_prop_stunt_track_dwlink_02",
    "stt_prop_stunt_track_dwlink",
    "stt_prop_stunt_track_cutout",
    "stt_prop_stunt_track_bumps",
    "stt_prop_stunt_target_small",
    "stt_prop_stunt_target",
    "stt_prop_stunt_soccer_goal",
    "stt_prop_stunt_landing_zone_01",
    "stt_prop_stunt_jump_loop",
    "stt_prop_stunt_jump45",
    "stt_prop_stunt_jump30",
    "stt_prop_stunt_jump15",
    "stt_prop_stunt_bblock_xl3",
    "stt_prop_stunt_bblock_huge_05",
    "stt_prop_stunt_bblock_hump_01",
    "stt_prop_stunt_bblock_huge_04",
    "stt_prop_stunt_bblock_huge_01",
    "stt_prop_stunt_bblock_huge_02",
    "stt_prop_stunt_bblock_huge_03",
    "stt_prop_stunt_track_dwslope30",
    "stt_prop_stunt_track_dwslope45",
    "stt_prop_stunt_track_dwturn",
    "stt_prop_stunt_track_dwuturn",
    "stt_prop_stunt_track_exshort",
    "stt_prop_stunt_track_fork",
    "stt_prop_stunt_track_funlng",
    "stt_prop_stunt_track_funnel",
    "stt_prop_stunt_track_hill",
    "stt_prop_stunt_track_hill2",
    "stt_prop_stunt_track_jump",
    "stt_prop_stunt_track_link",
    "stt_prop_stunt_track_otake",
    "stt_prop_stunt_track_sh15",
    "stt_prop_stunt_track_sh30",
    "stt_prop_stunt_track_sh45",
    "stt_prop_stunt_track_sh45_a",
    "stt_prop_stunt_track_short",
    "stt_prop_stunt_track_slope15",
    "stt_prop_stunt_track_slope30",
    "stt_prop_stunt_track_slope45",
    "stt_prop_stunt_track_st_01",
    "stt_prop_stunt_track_st_02",
    "stt_prop_stunt_track_start",
    "stt_prop_stunt_track_start_02",
    "stt_prop_stunt_track_straight",
    "stt_prop_stunt_track_straightice",
    "stt_prop_stunt_track_turn",
    "stt_prop_stunt_track_turnice",
    "stt_prop_stunt_track_uturn",
    "stt_prop_stunt_tube_crn",
    "prop_weed_02",
    "stt_prop_stunt_track_dwuturn",
    "ch3_12_animplane1_lod",
    "ch3_12_animplane2_lod",
    "hei_prop_hei_pic_pb_plane",
    "light_plane_rig",
    "prop_cs_plane_int_01",
    "prop_dummy_plane",
    "prop_mk_plane",
    "v_44_planeticket",
    "prop_planer_01",
    "ch3_03_cliffrocks03b_lod",
    "ch3_04_rock_lod_02",
    "csx_coastsmalrock_01_",
    "csx_coastsmalrock_02_",
    "csx_coastsmalrock_03_",
    "csx_coastsmalrock_04_",
    "mp_player_introck",
    "Heist_Yacht",
    "csx_coastsmalrock_05_",
    "mp_player_int_rock",
    "mp_player_introck",
    "prop_flagpole_1a",
    "prop_flagpole_2a",
    "prop_flagpole_3a",
    "prop_a4_pile_01",
    "cs2_10_sea_rocks_lod",
    "cs2_11_sea_marina_xr_rocks_03_lod",
    "prop_gold_cont_01",
    "prop_hydro_platform",
    "ch3_04_viewplatform_slod",
    "ch2_03c_rnchstones_lod",
    "proc_mntn_stone01",
    "prop_beachflag_le",
    "proc_mntn_stone02",
    "cs2_10_sea_shipwreck_lod",
    "des_shipsink_02",
    "prop_dock_shippad",
    "des_shipsink_03",
    "des_shipsink_04",
    "prop_mk_flag",
    "prop_mk_flag_2",
    "proc_mntn_stone03",
    "FreeModeMale01",
    "rsn_os_specialfloatymetal_n",
    "rsn_os_specialfloatymetal",
    "cs1_09_sea_ufo",
    "rsn_os_specialfloaty2_light2",
    "rsn_os_specialfloaty2_light",
    "rsn_os_specialfloaty2",
    "rsn_os_specialfloatymetal_n",
    "rsn_os_specialfloatymetal",
    "P_Spinning_Anus_S_Main",
    "P_Spinning_Anus_S_Root",
    "cs3_08b_rsn_db_aliencover_0001",
    "cs3_08b_rsn_db_aliencover_0001_a",
    "sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a",
    "rnbj_wallsigns_0001",
    "proc_sml_stones01",
    "proc_sml_stones02",
    "maverick",
    "Miljet",
    "proc_sml_stones03",
    "proc_stones_01",
    "proc_stones_02",
    "proc_stones_03",
    "proc_stones_04",
    "proc_stones_05",
    "proc_stones_06",
    "prop_coral_stone_03",
    "prop_coral_stone_04",
    "prop_gravestones_01a",
    "prop_gravestones_02a",
    "prop_gravestones_03a",
    "prop_gravestones_04a",
    "prop_gravestones_05a",
    "prop_gravestones_06a",
    "prop_gravestones_07a",
    "prop_gravestones_08a",
    "prop_gravestones_09a",
    "prop_gravestones_10a",
    "prop_prlg_gravestone_05a_l1",
    "prop_prlg_gravestone_06a",
    "test_prop_gravestones_04a",
    "test_prop_gravestones_05a",
    "test_prop_gravestones_07a",
    "test_prop_gravestones_08a",
    "test_prop_gravestones_09a",
    "prop_prlg_gravestone_01a",
    "prop_prlg_gravestone_02a",
    "prop_prlg_gravestone_03a",
    "prop_prlg_gravestone_04a",
    "prop_stoneshroom1",
    "prop_stoneshroom2",
    "v_res_fa_stones01",
    "test_prop_gravestones_01a",
    "test_prop_gravestones_02a",
    "prop_prlg_gravestone_05a",
    "FreemodeFemale01",
    "p_cablecar_s",
    "stt_prop_stunt_tube_l",
    "stt_prop_stunt_track_dwuturn",
    "p_spinning_anus_s",
    "prop_windmill_01",
    "hei_prop_heist_tug",
    "prop_air_bigradar",
    "p_oil_slick_01",
    "prop_dummy_01",
    "hei_prop_heist_emp",
    "p_tram_cash_s",
    "hw1_blimp_ce2",
    "prop_fire_exting_1a",
    "prop_fire_exting_1b",
    "prop_fire_exting_2a",
    "prop_fire_exting_3a",
    "hw1_blimp_ce2_lod",
    "hw1_blimp_ce_lod",
    "hw1_blimp_cpr003",
    "hw1_blimp_cpr_null",
    "hw1_blimp_cpr_null2",
    "prop_lev_des_barage_02",
    "hei_prop_carrier_defense_01",
    "prop_juicestand",
    "v_ilev_found_cranebucket",
    "p_cs_sub_hook_01_s",
    "hei_prop_heist_hook_01",
    "prop_rope_hook_01",
    "prop_sub_crane_hook",
    "prop_vehicle_hook",
    "prop_v_hook_s",
    "prop_dock_crane_02_hook",
    "prop_winch_hook_long",
    "prop_coathook_01",
    "prop_cs_sub_hook_01",
    "prop_windmill_01",
    "prop_Ld_ferris_wheel",
    "p_tram_crash_s",
    "p_oil_slick_01",
    "p_ld_stinger_s",
    "p_ld_soc_ball_01",
    "p_parachute1_s",
    "p_cablecar_s",
    "prop_beach_fire",
    "prop_lev_des_barge_02",
    "prop_lev_des_barge_01",
    "prop_sculpt_fix",
    "prop_flagpole_2b",
    "prop_flagpole_2c",
    "prop_winch_hook_short",
    "prop_flag_canada",
    "prop_flag_canada_s",
    "prop_flag_eu",
    "prop_flag_eu_s",
    "prop_flag_france",
    "prop_flag_france_s",
    "prop_flag_german",
    "prop_ld_hook",
    "prop_flag_german_s",
    "prop_flag_ireland",
    "prop_flag_ireland_s",
    "prop_flag_japan",
    "prop_flag_japan_s",
    "prop_flag_ls",
    "prop_flag_lsfd",
    "prop_flag_lsfd_s",
    "prop_cable_hook_01",
    "prop_flag_lsservices",
    "prop_flag_lsservices_s",
    "prop_flag_ls_s",
    "prop_flag_mexico",
    "prop_flag_mexico_s",
    "csx_coastboulder_00",
    "des_tankercrash_01",
    "des_tankerexplosion_01",
    "des_tankerexplosion_02",
    "des_trailerparka_02",
    "des_trailerparkb_02",
    "des_trailerparkc_02",
    "des_trailerparkd_02",
    "des_traincrash_root2",
    "des_traincrash_root3",
    "des_traincrash_root4",
    "des_traincrash_root5",
    "des_finale_vault_end",
    "des_finale_vault_root001",
    "des_finale_vault_root002",
    "des_finale_vault_root003",
    "des_finale_vault_root004",
    "des_finale_vault_start",
    "des_vaultdoor001_root001",
    "des_vaultdoor001_root002",
    "des_vaultdoor001_root003",
    "des_vaultdoor001_root004",
    "des_vaultdoor001_root005",
    "des_vaultdoor001_root006",
    "des_vaultdoor001_skin001",
    "des_vaultdoor001_start",
    "des_traincrash_root6",
    "prop_ld_vault_door",
    "prop_vault_door_scene",
    "prop_vault_door_scene",
    "prop_vault_shutter",
    "p_fin_vaultdoor_s",
    "v_ilev_bk_vaultdoor",
    "prop_gold_vault_fence_l",
    "prop_gold_vault_fence_r",
    "prop_gold_vault_gate_01",
    "prop_bank_vaultdoor",
    "des_traincrash_root7",
    "prop_flag_russia",
    "prop_flag_russia_s",
    "prop_flag_s",
    "ch2_03c_props_rrlwindmill_lod",
    "prop_flag_sa",
    "prop_flag_sapd",
    "prop_flag_sapd_s",
    "prop_flag_sa_s",
    "prop_flag_scotland",
    "prop_flag_scotland_s",
    "prop_flag_sheriff",
    "prop_flag_sheriff_s",
    "prop_flag_uk",
    "prop_yacht_lounger",
    "prop_yacht_seat_01",
    "prop_yacht_seat_02",
    "prop_yacht_seat_03",
    "marina_xr_rocks_02",
    "marina_xr_rocks_03",
    "prop_test_rocks01",
    "prop_test_rocks02",
    "prop_test_rocks03",
    "prop_test_rocks04",
    "marina_xr_rocks_04",
    "marina_xr_rocks_05",
    "marina_xr_rocks_06",
    "prop_yacht_table_01",
    "csx_searocks_02",
    "csx_searocks_03",
    "csx_searocks_04",
    "csx_searocks_05",
    "csx_searocks_06",
    "p_yacht_chair_01_s",
    "p_yacht_sofa_01_s",
    "prop_yacht_table_02",
    "csx_coastboulder_00",
    "csx_coastboulder_01",
    "csx_coastboulder_02",
    "csx_coastboulder_03",
    "csx_coastboulder_04",
    "csx_coastboulder_05",
    "csx_coastboulder_06",
    "csx_coastboulder_07",
    "csx_coastrok1",
    "csx_coastrok2",
    "csx_coastrok3",
    "csx_coastrok4",
    "csx_coastsmalrock_01",
    "csx_coastsmalrock_02",
    "csx_coastsmalrock_03",
    "csx_coastsmalrock_04",
    "csx_coastsmalrock_05",
    "prop_yacht_table_03",
    "prop_flag_uk_s",
    "prop_flag_us",
    "prop_flag_usboat",
    "prop_flag_us_r",
    "prop_flag_us_s",
    "p_gasmask_s",
    "prop_fnclink_05crnr1",
    "xs_prop_hamburgher_wl",
    "sr_prop_spec_tube_xxs_01a",
    "prop_cs_dildo_01",
    "prop_container_01a",
    "prop_contnr_pile_01a",
    "ce_xr_ctr2",
    "prop_parking_hut_2",
    "csx_seabed_rock3_",
    "db_apart_03_",
    "db_apart_09_",
    "prop_gascage01",
    "p_crahsed_heli_s",
    "prop_rock_4_big2",
    "prop_flamingo",
    -- PEDS
    "s_m_y_swat_01",
    "a_m_o_acult_01",
    "ig_wade",
    "s_m_y_hwaycop_01",
    "A_M_Y_ACult_01",
    "s_m_m_movalien_01",
    "s_m_m_movallien_01",
    "u_m_y_babyd",
    "CS_Orleans",
    "A_M_Y_ACult_01",
    "S_M_M_MovSpace_01",
    "U_M_Y_Zombie_01",
    "s_m_y_blackops_01",
    "a_f_y_topless_01",
    "a_c_boar",
    "a_c_cat_01",
    "a_c_chickenhawk",
    "a_c_chimp",
    "s_f_y_hooker_03",
    "a_c_chop",
    "a_c_cormorant",
    "a_c_cow",
    "a_c_coyote",
    "a_c_crow",
    "a_c_dolphin",
    "a_c_fish",
    "s_f_y_hooker_01",
    "a_c_hen",
    "a_c_humpback",
    "a_c_killerwhale",
    "a_c_pigeon",
    "a_c_rabbit_01",
    "a_c_rat",
    "a_c_rhesus",
    "a_c_rottweiler",
    "a_c_sharkhammer",
    "a_c_sharktiger",
    "a_c_stingray",
    "a_c_westy",
    "CS_Orleans"
}
Config.DeletedExplosions = {
    0,
    1,
    2,
    3,
    4,
    5,
    25,
    32,
    33,
    35,
    36,
    37,
    38
}
Config.ModelChange = {
    "a_m_y_mexthug_01",
    "a_c_cat_01",
    "a_c_boar",
    "a_c_sharkhammer",
    "a_c_coyote",
    "a_c_chimp",
    "a_c_cow",
    "a_c_deer",
    "a_c_dolphin",
    "a_c_rat",
    "a_c_fish",
    "a_c_hen",
    "a_c_humpback",
    "a_c_killerwhale",
    "a_c_rabbit_01",
    "a_c_rhesus",
    "a_c_sharktiger",
    "u_m_y_zombie_01"
}
Config.WeaponDamagesTable = {
    [-1357824103] = 34, -- AdvancedRifle
    [453432689] = 26, -- Pistol
    [1593441988] = 27, -- CombatPistol
    [584646201] = 25, -- APPistol
    [-1716589765] = 51, -- Pistol50
    [-1045183535] = 160, -- Revolver
    [-1076751822] = 28, -- SNSPistol
    [-771403250] = 40, -- HeavyPistol
    [137902532] = 34, -- VintagePistol
    [324215364] = 21, -- MicroSMG
    [736523883] = 22, -- SMG
    [-270015777] = 23, -- AssaultSMG
    [-1121678507] = 22, -- MiniSMG
    [-619010992] = 27, -- MachinePistol
    [171789620] = 28, -- CombatPDW
    [487013001] = 29, -- PumpShotgun
    [2017895192] = 40, -- SawnoffShotgun
    [-494615257] = 32, -- AssaultShotgun
    [-1654528753] = 14, -- BullpupShotgun
    [984333226] = 117, -- HeavyShotgun
    [-1074790547] = 30, -- AssaultRifle
    [-2084633992] = 32, -- CarbineRifle
    [-1063057011] = 32, -- SpecialCarbine
    [2132975508] = 32, -- BullpupRifle
    [1649403952] = 34, -- CompactRifle
    [-1660422300] = 40, -- MG
    [2144741730] = 45, -- CombatMG
    [1627465347] = 34, -- Gusenberg
    [100416529] = 101, -- SniperRifle
    [205991906] = 216, -- HeavySniper
    [-952879014] = 65, -- MarksmanRifle
    [1119849093] = 30, -- Minigun
    [-1466123874] = 165, -- Musket
    [911657153] = 1, -- StunGun
    [1198879012] = 10, -- FlareGun
    [-598887786] = 220, -- MarksmanPistol
    [1834241177] = 30, -- Railgun
    [-275439685] = 30, -- DoubleBarrelShotgun
    [-1746263880] = 81, -- Double Action Revolver
    [-2009644972] = 30, -- SNS Pistol Mk II
    [-879347409] = 200, -- Heavy Revolver Mk II
    [-1768145561] = 32, -- Special Carbine Mk II
    [-2066285827] = 33, -- Bullpup Rifle Mk II
    [1432025498] = 32, -- Pump Shotgun Mk II
    [1785463520] = 75, -- Marksman Rifle Mk II
    [961495388] = 40, -- Assault Rifle Mk II
    [-86904375] = 33, -- Carbine Rifle Mk II
    [-608341376] = 47, -- Combat MG Mk II
    [177293209] = 230, -- Heavy Sniper Mk II
    [-1075685676] = 32, -- Pistol Mk II
    [2024373456] = 25 -- SMG Mk II
}
